DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GROUP_MEMBERS;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS SQUARES;
DROP TABLE IF EXISTS DRAWINGS;

CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER RIMARY KEY ASC NOT NULL UNIQUE,
    username TEXT,
    password TEXT
);

CREATE TABLE IF NOT EXISTS GROUPS (
    id INTEGER RIMARY KEY ASC NOT NULL UNIQUE,
    name TEXT,
    daily_start_time TEXT,
    daily_close_time TEXT
);

CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
    user_id INTEGER REFERENCES USERS(id),
    group_id INTEGER REFERENCES GROUPS(id),
    PRIMARY KEY(user_id, group_id)
);

CREATE TABLE IF NOT EXISTS DRAWINGS (
    id INTEGER RIMARY KEY ASC NOT NULL UNIQUE,
    group_id INTEGER REFERENCES GROUPS(id),
    init_topic TEXT,
    current_topic TEXT,
    date TEXT,
    last_updated TEXT
);

CREATE TABLE IF NOT EXISTS SQUARES (
    user_id INTEGER REFERENCES USERS(id),
    drawing_id INTEGER REFERENCES DRAWINGS(id),
    file_path TEXT,
    complete INTEGER,
    PRIMARY KEY(user_id, drawing_id)
);

